version: "3"

services:
  config-server:
    image: springcommunity/spring-petclinic-config-server:latest  # Utilisez l'image de production pour l'instant
    container_name: staging-config-server
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-I", "http://staging-config-server:8888"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 8889:8888

  grafana-server:
    build: ./docker/grafana
    container_name: staging-grafana-server
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 3001:3000

  prometheus-server:
    build: ./docker/prometheus
    container_name: staging-prometheus-server
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 9092:9090